### ISSUE TITLE
Memory Consumption does not Reduce after the PDF is written

### ISSUE THREAD

**Issue by neelesharoraqainfotech** [devicarus/image-to-pdf#4]
The memory that the package uses is not cleared after the script is completed. The node server needs to be restarted in order to clear memory. Is there any way, we can clear the memory manually? Currently, my node server uses around 6 GB of memory after running the script.

**Comment by devicarus** [comment]
Sorry for replying almost 3 years later. I couldn't replicate this, but sounds like an issue of the underlying package [pdfkit](https://github.com/foliojs/pdfkit) - to anyone encountering this, create an issue there, thanks
