### ISSUE TITLE
Add typescript support

### ISSUE THREAD

**Issue by Ankan-cyber** [devicarus/image-to-pdf#8]
I am using this in nextjs and with ts. so its throwing error. could you guys add ts support. I seen that you guys using pdfkit under the hood so pdf kit supports ts with the @types/pdfkit installation module

**Comment by devicarus** [comment]
Finally added in v3.0.0, sorry it took almost 2 years 😅

**Comment by Ankan-cyber** [comment]
no worry's 😊
